sudo: required
services:
- docker
language: java
env:
  global:
  - REGISTRY_USER=rsosem
  - DOCKER_IMAGE=introduction:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - DOCKER_IMAGE_FULL_PATH=kuharskimojster/introduction
  - secure: JiBpCuhyfDj/dbyR1dY60vfAsgGqwuWHmgJt2SjRm8+fOZiCfeZ9Xh+rIlBYlTA+RB4GumkJ6/AKp9dbBRdXWCvmWqRm19dgfcHR3yQtjXb/yJ3q5fYoIKTDoAFQcUF75ZNVNnPjJ8w1KK+rzFyg4/7KcVuCEL+N7WprS5xC92kf0cpT2ERPgYbJvtaefr5MlIm7ptJBl033cK/tj8Fu7vSt2q1jzXnQixXi5Q1xwvcL1mLTyN6Ao1F9kniqO2MSUgeYEyi41H9ON+pdZMM8GrZRV65NfmD+YFSoPg/CBTlNqY2a2q2pgBYaa8u/RkAOXKZ/db8aI5q8tVAi9VpTXUbHLDlzFB3uZJ1xbFx7p22I46ktTDIq9SWQZzeQFXs4j1Noijd6R2epcZBA7zgJ6FPqSuoGt0ljz3J4+4UfncYfOuMrPsmnrEGtMKP9PKjlm+YSNbxmp+qfIcucElbOoI/5Z3itQ6INd9D4ftQaD8ICd5vJaeCVMhQXmVUqUBJEeXPV9itGEimsVpuMmEM17fdVrDIkCzn0FUK6O/urIeMCXbgbPTJwy2svAsWpz6ozqdq1aitUEVDkrMDivRGjnMH0UIFEJsp2fj82xboU8ZYcdng809n4vv/UHsF4FK/YNJwH6E93lqedAitnbBRbLKm6Cl+ANzE0IISMcH4HbHM=
script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .
after_script:
- docker images
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
after_success:
- docker push "$DOCKER_IMAGE"
